import { Block } from "prismarine-block";
import { Vec3 } from "vec3";

export = loader;
declare function loader(mcVersion: number): {
    new (): {
        sectionMask: number;
        sections: any[];
        biomes: any[];
        skyLightMask: number;
        blockLightMask: number;
        skyLightSections: any[];
        blockLightSections: any[];
        toJson(): string;
        initialize(func: any): void;
        getBlock(pos: Vec3): any;
        setBlock(pos: Vec3, block: Block): void;
        getBlockType(pos: Vec3): any;
        getBlockData(pos: Vec3): any;
        getBlockStateId(pos: Vec3): any;
        getBlockLight(pos: Vec3): any;
        getSkyLight(pos: Vec3): any;
        getBiome(pos: Vec3): any;
        getBiomeColor(pos: Vec3): {
            r: number;
            g: number;
            b: number;
        };
        setBlockType(pos: Vec3, id: any): void;
        setBlockData(pos: Vec3, data: any): void;
        setBlockStateId(pos: Vec3, stateId: any): void;
        setBlockLight(pos: Vec3, light: any): void;
        setSkyLight(pos: Vec3, light: any): void;
        setBiome(pos: Vec3, biome: any): void;
        setBiomeColor(pos: Vec3, r: number, g: number, b: number): void;
        getMask(): number;
        dump(): Buffer;
        loadBiomes(biomes: any): void;
        dumpBiomes(biomes: any): any[];
        load(data: any, bitMap?: number): void;
        loadLight(data: any, skyLightMask: any, blockLightMask: any, emptySkyLightMask?: number, emptyBlockLightMask?: number): void;
        dumpLight(): Buffer;
    };
    fromJson(j: any): {
        sectionMask: number;
        sections: any[];
        biomes: any[];
        skyLightMask: number;
        blockLightMask: number;
        skyLightSections: any[];
        blockLightSections: any[];
        toJson(): string;
        initialize(func: any): void;
        getBlock(pos: Vec3): any;
        setBlock(pos: Vec3, block: any): void;
        getBlockType(pos: Vec3): any;
        getBlockData(pos: Vec3): any;
        getBlockStateId(pos: Vec3): any;
        getBlockLight(pos: Vec3): any;
        getSkyLight(pos: Vec3): any;
        getBiome(pos: Vec3): any;
        getBiomeColor(pos: Vec3): {
            r: number;
            g: number;
            b: number;
        };
        setBlockType(pos: Vec3, id: any): void;
        setBlockData(pos: Vec3, data: any): void;
        setBlockStateId(pos: Vec3, stateId: any): void;
        setBlockLight(pos: Vec3, light: any): void;
        setSkyLight(pos: Vec3, light: any): void;
        setBiome(pos: Vec3, biome: any): void;
        setBiomeColor(pos: Vec3, r: number, g: number, b: number): void;
        getMask(): number;
        dump(): Buffer;
        loadBiomes(biomes: any): void;
        dumpBiomes(biomes: any): any[];
        load(data: any, bitMap?: number): void;
        loadLight(data: any, skyLightMask: any, blockLightMask: any, emptySkyLightMask?: number, emptyBlockLightMask?: number): void;
        dumpLight(): Buffer;
    };
};
