declare function _exports(Block: any, mcData: any): {
    new (): {
        sectionMask: number;
        sections: any[];
        biomes: any[];
        skyLightMask: number;
        blockLightMask: number;
        skyLightSections: any[];
        blockLightSections: any[];
        toJson(): string;
        initialize(func: any): void;
        getBlock(pos: any): any;
        setBlock(pos: any, block: any): void;
        getBlockType(pos: any): any;
        getBlockData(pos: any): any;
        getBlockStateId(pos: any): any;
        getBlockLight(pos: any): any;
        getSkyLight(pos: any): any;
        getBiome(pos: any): any;
        getBiomeColor(pos: any): {
            r: number;
            g: number;
            b: number;
        };
        setBlockType(pos: any, id: any): void;
        setBlockData(pos: any, data: any): void;
        setBlockStateId(pos: any, stateId: any): void;
        setBlockLight(pos: any, light: any): void;
        setSkyLight(pos: any, light: any): void;
        setBiome(pos: any, biome: any): void;
        setBiomeColor(pos: any, r: any, g: any, b: any): void;
        getMask(): number;
        dump(): Buffer;
        loadBiomes(biomes: any): void;
        dumpBiomes(biomes: any): any[];
        load(data: any, bitMap?: number): void;
        loadLight(data: any, skyLightMask: any, blockLightMask: any, emptySkyLightMask?: number, emptyBlockLightMask?: number): void;
        dumpLight(): Buffer;
    };
    fromJson(j: any): {
        sectionMask: number;
        sections: any[];
        biomes: any[];
        skyLightMask: number;
        blockLightMask: number;
        skyLightSections: any[];
        blockLightSections: any[];
        toJson(): string;
        initialize(func: any): void;
        getBlock(pos: any): any;
        setBlock(pos: any, block: any): void;
        getBlockType(pos: any): any;
        getBlockData(pos: any): any;
        getBlockStateId(pos: any): any;
        getBlockLight(pos: any): any;
        getSkyLight(pos: any): any;
        getBiome(pos: any): any;
        getBiomeColor(pos: any): {
            r: number;
            g: number;
            b: number;
        };
        setBlockType(pos: any, id: any): void;
        setBlockData(pos: any, data: any): void;
        setBlockStateId(pos: any, stateId: any): void;
        setBlockLight(pos: any, light: any): void;
        setSkyLight(pos: any, light: any): void;
        setBiome(pos: any, biome: any): void;
        setBiomeColor(pos: any, r: any, g: any, b: any): void;
        getMask(): number;
        dump(): Buffer;
        loadBiomes(biomes: any): void;
        dumpBiomes(biomes: any): any[];
        load(data: any, bitMap?: number): void;
        loadLight(data: any, skyLightMask: any, blockLightMask: any, emptySkyLightMask?: number, emptyBlockLightMask?: number): void;
        dumpLight(): Buffer;
    };
};
export = _exports;
